### PR TITLE
Scaffolding for building, testing, and returning client from server.

### LINKED ISSUE #4: Add an html based client
Add an HTML page that connects to a NodeJS socket to engage a game.

### PR DESCRIPTION
**Pull request by davidwesst**
Resolves #4. Complete setup of server and client scaffolding, with testing for both client and server.

**NOTE** -- Moved the connection functionality to #11 to reduce the scope of #4 to focus on the setup of the HTML-based client and the overall scaffolding of the project.

### CODE REVIEW

**Comment by davidwesst** [comment]
Before merging, please pull the code into your local repository to ensure that it works as expected. You can pull from my branch using ```git pull davidwesst dev-setupserver``` where ```davidwesst``` is a remote repository pointing to my fork.

**Comment by Chrinkus** [comment]
I've pulled in the code. How do I test it? What file launches the server?

**Comment by davidwesst** [comment]
npm install
npm start
You might need to install a few things globally, more specifically:
express, mocha-phantomjs, phantomjs

**Comment by Chrinkus** [comment]
npm install -g express?

**Comment by davidwesst** [comment]
Yup.

**Comment by Chrinkus** [comment]
After installing dependencies I had an error when trying to $ npm start:
node --harmony dist/index.js
Thoughts?

**Comment by davidwesst** [comment]
My bad. You need to build the project
```
grunt
npm start
```

**Comment by Chrinkus** [comment]
typing grunt on its own gives me an error.

**Comment by davidwesst** [comment]
Try installing the grunt-cli globally:
```npm install -g grunt-cli```
Then try again.

**Comment by Chrinkus** [comment]
Ok, done. After installing grunt, attempting to execute grunt returns an error saying that grunt-mocha-phantomjs is not installed, attempting to reinstall it tells me it is.

Anyway, npm start works now.

Shoot-Out!! server running on port 3001

Is that the intended output?

**Comment by davidwesst** [comment]
Yep! Now open your favourite web browser and navigate to http://localhost:3001/game while that is still running.

**Comment by Chrinkus** [comment]
WOW nice!!

**Comment by davidwesst** [comment]
....and THAT is how you pull-request like a boss (and a serious professional). **drops the mic**

For real man, good work on this! We need to do this sort of thing every time we are committing changes.

**Pull request merged**
